
version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/app" 
    schedule:
      interval: "monthly"
    assignees:
      - "ShubhamOulkar"
    labels:
      - "dependencies"
    commit-message:
      prefix: "dep:"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
