<!-- example env variables -->
VITE_OPEN_WEATHER_MAP_ID=
VITE_REVESE_GEOCODING=
VITE_GEOCODING_NAME=
VITE_IP_LOOKUP=
VITE_OPEN_METEO_WEATHER=
VITE_OPEN_METEO_AQI=
VITE_OPEN_METEO_DAILY=
VITE_OPEN_METEO_HOURLY=
VITE_FAVORITES_STORAGE_KEY=