name: Test and Build

on:
  push:
    branches: [ "new-feature" ]
  pull_request:
    branches: [ "new-feature" ]

permissions:
  contents: read
  actions: read

jobs:
  # Build
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Git Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 10.9.0

      - name: Set up Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: './app/.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: './app/pnpm-lock.yaml'

      - name: Install packages
        run: pnpm install --frozen-lockfile
        working-directory: ./app

      - name: Build
        run: pnpm run build
        working-directory: ./app

  # Test
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # windows-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Git Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 10.9.0

      - name: Set up Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: './app/.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: './app/pnpm-lock.yaml'

      - name: Install packages
        run: pnpm install --frozen-lockfile
        working-directory: ./app

      - name: Run Biome (format and lint)
        run: pnpm clean:ci
        working-directory: ./app

      - name: Run Unit Tests
        run: pnpm test
        working-directory: ./app

  # Upload test results to codecov
  upload-test:
    name: Upload test
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - name: Git Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set up pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        version: 10.9.0

    - name: Set up Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version-file: './app/.nvmrc'
        cache: 'pnpm'
        cache-dependency-path: './app/pnpm-lock.yaml'

    - name: Install packages
      run: pnpm install --frozen-lockfile
      working-directory: ./app

    - name: Run tests
      run: pnpm test:ci
      working-directory: ./app
    
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

   # Log success
  log-success:
    name: Log success
    runs-on: ubuntu-latest
    needs: [build, test, upload-test]
    steps:
      - name: Echo success message
        run: echo "🎉 build, test and upload test result jobs passed successfully!"
